#!/bin/bash

set -euo pipefail
set -o errexit
set -o errtrace

script_path="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

export PYTHONPATH="${PYTHONPATH:+${PYTHONPATH}:}${script_path}"

exec python3 "${script_path}"/run.py
